Размечен Index и Catalog
htmlacademy-htmlcss/1224279-sedona-30 pull request #2
Opened 2021-01-24 14:17 UTC by potapov11

2021-01-24 20:26 UTC, vovaborisenko requested changes
## разметка сделана хорошо

но не хватает несколько элементов (см. скрины):
- на главной карты и формы;
- на внутренней: панели управления найденных элементов.
![image](https://user-images.githubusercontent.com/30496847/105642349-432e1480-5e9a-11eb-8c85-4d9b5d84227c.png)
![image](https://user-images.githubusercontent.com/30496847/105642355-4de8a980-5e9a-11eb-87a1-4e490cb07f3a.png)

также очень прошу перед каждой отправкой на пулреквета проверяй свой код на валидность через https://validator.w3.org/#validate_by_input.

каждое задание нужно делать в разных коммитах. а желательно отправлять на проверку по одному заданию. т.к. все коммиты автоматически летят в одни пулрвест.

если  для какого-то блока описана ошибка, и этот блок повторяется на страницах или странице, то эту ошибку нужно исправить для всех подобных, похожих и повторяющихся блоков.

2021-01-24 20:26 UTC, vovaborisenko commented on catalog.html
> +            </li>
не хватает тегов, которые обозначат звезды

2021-01-24 20:26 UTC, vovaborisenko commented on catalog.html
> +        </nav>
- неверный порядок пунктов меню.
- страница для пункта меню "Гостиницы" - существует. нужно написать на нее правильную ссылку.
- все пункты меню нужно объединить под одним тегом nav и ul. (стилями мы придем к результату отображения как на макете).
- необходимо соблюдать табуляцию (отступы). сейчас у тегов li неверная табуляция.

- **в описании к ДЗ разделе ВАЖНО написано:**
Не нужно вырезать изображения. Используйте вместо них заглушки, например: `<img src="https://via.placeholder.com/150x100" alt="">`, где 150x100 в адресе картинки — это её размер. Нарезать графику из макетов вы научитесь в следующем разделе.

Из коммита нужно убрать лишние файлы (файлы изображений). у себя можешь их где-то сохранить.

2021-01-24 20:26 UTC, vovaborisenko commented on catalog.html
> +          <a href="ТЕЛ:+74956660166">ТЕЛ: +7(495) 666-01-66</a>
в href неверно написана ссылка. правильно писать `href="tel:+74956660166"`

2021-01-24 20:26 UTC, vovaborisenko commented on catalog.html
> +            <li><a href="twitter.com"><img src="img/youtube.svg" alt="лого ютуб" width="22" height="16"></a></li>
ссылки здесь не должны поавторяться

2021-01-24 20:26 UTC, vovaborisenko commented on catalog.html
> +          <a href="htmlacademy.ru"><img src="img/logo-htmlacademy.svg" alt="лого академии"  width="115" height="41">></a>
есть лишняя скобка в 122 строке

2021-01-24 20:26 UTC, vovaborisenko commented on catalog.html
> +          <a href="htmlacademy.ru"><img src="img/logo-htmlacademy.svg" alt="лого академии"  width="115" height="41">></a>
не выполнено требование ТЗ пункт 3.8 https://up.htmlacademy.ru/htmlcss/30/project/sedona#sedona-3-8

2021-01-25 21:39 UTC, vovaborisenko requested changes
## часть ошибок выполнено - это хорошо)
но не все и не совсем правильно.

в изменениях к пулрекветсту https://github.com/htmlacademy-htmlcss/1224279-sedona-30/pull/2/files должны остаться только файлы: index.html, catalog.html, readme.md и всё (файлы картинок нужно удалить из пулрекветста, для этого нужно закоммитить их удаление из проекта (для себя их можно сохранить вне проекта)). ВСЕ-ВСЕ картинки нужно сделать через заглушки (как описано в задании).

и еще одно просьба: оставлять какой-нибудь комментарий о выполнении или о не согласии к моим комментариям.

2021-01-25 21:39 UTC, vovaborisenko commented on index.html
> +          <p>Дети: 0</p>
это поля нужно реализовать инпутами

2021-01-25 21:39 UTC, vovaborisenko commented on index.html
> +        <a href="https://htmlacademy.ru/intensive"><img src="img/logo-htmlacademy.svg" alt="лого академии"  width="115" height="41"></a>
неверная ссылка

2021-01-25 21:39 UTC, vovaborisenko commented on catalog.html
> +            <li><a href="blank.html">Гостиницы</a></li>
ссылка для пунтка меню "Гостиницы" существует (см. как сделано в файле index.html)

2021-01-25 21:39 UTC, vovaborisenko commented on catalog.html
> +        </div>
не все элементы реализованы в этом блоке (не хватает стрелок)

2021-01-25 21:39 UTC, vovaborisenko commented on catalog.html
> +          <a href="https://htmlacademy.ru/intensive"><img src="img/logo-htmlacademy.svg" alt="лого академии"  width="115" height="41"></a>
неверная ссылка (см. пункт 3.8 ТЗ)

2021-01-26 17:05 UTC, potapov11 commented on index.html
> +          <p>Дети: 0</p>
Выполнено

2021-01-26 17:06 UTC, potapov11 commented on index.html
> +        <a href="https://htmlacademy.ru/intensive"><img src="img/logo-htmlacademy.svg" alt="лого академии"  width="115" height="41"></a>
Исправлено

2021-01-26 17:06 UTC, potapov11 commented on catalog.html
> +            <li><a href="blank.html">Гостиницы</a></li>
Сделал

2021-01-26 17:06 UTC, potapov11 commented on catalog.html
> +        </div>
Разметил тегами span

2021-01-26 17:06 UTC, potapov11 commented on catalog.html
> +          <a href="https://htmlacademy.ru/intensive"><img src="img/logo-htmlacademy.svg" alt="лого академии"  width="115" height="41"></a>
Исправил

2021-01-26 20:54 UTC, vovaborisenko requested changes
очень прошу перед каждой отправкой на проверку проверяй свой код на валидность через https://validator.w3.org/#validate_by_input.

во всех файлах должна быть табуляция в два пробела, особенно касается файла catalog.html. чтобы табуляция для этого проекта выставлялась автоматически нужно установить расширение для vs code (см. скрин)
![image](https://user-images.githubusercontent.com/30496847/105902866-41965500-6030-11eb-8262-3e295eaa22a0.png)

в конце файла всегда должна оставаться одна пустая строка (ровно одна)

2021-01-26 20:54 UTC, vovaborisenko commented on Readme.md
> +- Наставник: [Владимир Борисенко] (https://htmlacademy.ru/profile/id1310789).
чтобы образовалась ссылка нужно между `]` и `(` убрать пробел

2021-01-26 20:54 UTC, vovaborisenko commented on catalog.html
> +            <button type="button">Показать</button>
пусть по нажатию на эту кнопку отправляется форма. для этого нужно изменить тип кнопки

2021-01-26 20:54 UTC, vovaborisenko commented on catalog.html
> +        <form action="https://echo.htmlacademy.ru">
запиши метод отправки формы `POST`

2021-01-26 20:54 UTC, vovaborisenko commented on catalog.html
> +            <span></span>
здесь должны быть кнопки

2021-01-26 20:54 UTC, vovaborisenko commented on index.html
> +          </form>
- добавь значение для action;
- метод отправки `POST`;
- оформи как надо поля ввода через теги label, у полей должен быть name;
- тег input не является парным, значит </input> - лишнее;
- кнопка должна отправлять форму.

2021-01-27 19:11 UTC, potapov11 commented on index.html
> +          </form>
Выполнили

2021-01-27 19:11 UTC, potapov11 commented on catalog.html
> +            <span></span>
Сделали

2021-01-27 19:12 UTC, potapov11 commented on catalog.html
> +        <form action="https://echo.htmlacademy.ru">
Записано

2021-01-27 19:12 UTC, potapov11 commented on catalog.html
> +            <button type="button">Показать</button>
Сделано

2021-01-27 19:12 UTC, potapov11 commented on Readme.md
> +- Наставник: [Владимир Борисенко] (https://htmlacademy.ru/profile/id1310789).
Убрано

2021-01-27 20:40 UTC, vovaborisenko reviewed
## все отлично

2021-01-27 20:42 UTC, merged

2021-01-27 20:43 UTC, vovaborisenko commented
не забудь сделать пул из ветки мастер мастер-репозитория в свой форк