ДЗ по стилизации
htmlacademy-htmlcss/1224279-sedona-30 pull request #4
Opened 2021-02-07 15:54 UTC by potapov11

2021-02-07 16:33 UTC, vovaborisenko reviewed
# хорошо все написал, но немного есть излишнего

- исправь все мои замечания по коду;
- для всех кнопок сделай uppercase.

2021-02-07 16:33 UTC, vovaborisenko commented on catalog.html
> +<body class="page-body">
- пропали фавиконки. нужно вернуть;
- отступы кода нужно поправить у `body`;
- `<meta charset="utf-8">` этот мета-тег должен идти первым `<head>`;
- пропал этот мета-тег: `<meta name="viewport" content="width=device-width, initial-scale=1.0">`. нужно вернуть

2021-02-07 16:33 UTC, vovaborisenko commented on catalog.html
> +        <li class="header_nav_item"><a class="header_nav_link" href="blank.html">Информация</a></li>
`<body class="page-body">` здесь класс через дефис
`<nav class="header_nav">` здесь и далее во всем документе класс через нижнее подчеркивание

нужно соблюдать один стиль в написании кода. необходимо либо все классы писать через дефис, или все классы через нижнее подчеркивание. (лучше через дефис)

2021-02-07 16:33 UTC, vovaborisenko commented on css/style.css
> +  font-family: "PT Sans", "Georgia", serif;
`font-family: serif;` это шрифт с засечками. в макете он без засечек. значит нужно `serif` поменять на `sans-serif`.

2021-02-07 16:33 UTC, vovaborisenko commented on css/style.css
> +}
такие стили противоречат [Д25. Нет глобальных стилей тегов](https://up.htmlacademy.ru/htmlcss/30/criteries#d25) нужно исправить

2021-02-07 16:33 UTC, vovaborisenko commented on css/style.css
> +}
`font-family` уже указан у родителя. это свойство наследуется. нужно везде убрать его и оставить только у `body` или `:root`. также установи основному родителю (`body` или `:root`) `font-weight: 400` и удали везде его где  `font-weight: 400`. в макете основной текст с размером 14px и весь текст прописными буквами.

в итоге пропиши родителю: `font-family`, `font-style`, `font-weight: 400`, `font-size: 14px`, `text-transform: uppercase` и везде где наследуются эти стили нужно убрать эти свойства.

2021-02-07 16:33 UTC, vovaborisenko commented on css/style.css
> +} */
такие "мертвые" куски кода не коммить. нужно удалить

2021-02-07 18:58 UTC, potapov11 commented on catalog.html
> +<body class="page-body">
Исправлено

2021-02-07 18:58 UTC, potapov11 commented on catalog.html
> +        <li class="header_nav_item"><a class="header_nav_link" href="blank.html">Информация</a></li>
Буду придерживаться с нижним подчеркиванием. Исправлено

2021-02-08 02:05 UTC, potapov11 commented on css/style.css
> +  font-family: "PT Sans", "Georgia", serif;
Сделано

2021-02-08 02:10 UTC, potapov11 commented on css/style.css
> +}
исправлено

2021-02-08 02:22 UTC, potapov11 commented on css/style.css
> +}
Усвоено, исправлено

2021-02-08 02:22 UTC, potapov11 commented on css/style.css
> +} */
Удалено!)

2021-02-08 20:19 UTC, vovaborisenko commented on css/style.css
> +}
не исправлено, этот код остался

2021-02-08 20:22 UTC, vovaborisenko commented on catalog.html
> +<body class="page-body">
не исправлен второй пункт: отступы кода нужно поправить у body.
сравни как это в index.hml и как в catalog.html (в index.html - верно)

2021-02-08 20:32 UTC, vovaborisenko requested changes
часть ошибок не исправлено, смотри выше в комментариях.
также добавились новые ошибки

2021-02-08 20:32 UTC, vovaborisenko commented on css/style.css
> +}
если так писать стили, то в итоге будут повторяться селекторы и будет сложно отследить, где что за что отвечает. (уже повторяется селектор `.social_item`, а дальше будет еще больше)

на данном этапе (в данной домашке) эти стили списка лишние - удали (чтобы не запутаться в селектарах). и `list-style` лучше задавать списку, а не элементам списка.

2021-02-08 20:32 UTC, vovaborisenko commented on css/style.css
> +}
эта часть кода дублируется в 88 строке

2021-02-08 20:32 UTC, vovaborisenko commented on img/Group 1.svg
> +</svg>
этот файл лишний

2021-02-08 20:32 UTC, vovaborisenko commented on img/Shape.svg
> +</svg>
этот файл лишний

2021-02-09 16:29 UTC, potapov11 commented on css/style.css
> +}
Удалены селекторы

2021-02-09 16:30 UTC, potapov11 commented on css/style.css
> +}
Лишняя часть удалена

2021-02-09 16:32 UTC, potapov11 commented on img/Shape.svg
> +</svg>
удалил

2021-02-09 18:09 UTC, merged