дз flexBox
htmlacademy-htmlcss/1224279-sedona-30 pull request #6
Opened 2021-02-22 19:56 UTC by potapov11

2021-02-23 16:00 UTC, vovaborisenko requested changes
как я вижу с флексами ты разобрался, хорошо!)

вот пару правок, которые улучшат твою верстку:
![image](https://user-images.githubusercontent.com/30496847/108870568-4affe680-7609-11eb-9ee8-e0507979f652.png)
![image](https://user-images.githubusercontent.com/30496847/108870602-505d3100-7609-11eb-8c45-d4c36496d51b.png)

2021-02-23 16:00 UTC, vovaborisenko commented on catalog.html
> +      Header
без `<!--` и `-->` текст виден на странице. зачем он должен быть виден?

2021-02-23 16:00 UTC, vovaborisenko commented on css/style.css
> +}
так запрещено писать по критерию Д25 https://up.htmlacademy.ru/htmlcss/30/criteries#d25

2021-02-23 16:00 UTC, vovaborisenko commented on css/style.css
> +}
для отступов между элементами списка воспользуйся методом, который я описал на скрине для соцсетей

2021-02-23 16:00 UTC, vovaborisenko commented on css/style.css
> +}
отредактируй порядок css свойств

2021-02-25 16:27 UTC, potapov11 commented on catalog.html
> +      Header
Исправлено

2021-02-25 16:27 UTC, potapov11 commented on css/style.css
> +}
переделал

2021-02-25 16:29 UTC, potapov11 commented on css/style.css
> +}
Исправлено

2021-02-25 16:31 UTC, potapov11 commented on css/style.css
> +}
Сделано

2021-02-25 16:44 UTC, vovaborisenko reviewed
# отлично справился!!!

2021-02-25 16:44 UTC, vovaborisenko commented on css/style.css
> +
пустую строку 310 нужно удалить

2021-02-25 16:45 UTC, merged